feat(app-deploy): add dockerfile option and rewrite description
tsuru/tsuru-client pull request #195
Opened 2023-02-02 19:56 UTC by nettoclaudio

2023-02-14 22:05 UTC, tcarreira requested changes

2023-02-16 14:02 UTC, nettoclaudio commented on tsuru/client/build.go
> +func uploadFiles(context *cmd.Context, filesOnly bool, request *http.Request, buf *safe.Buffer, body *safe.Buffer, values url.Values, archive io.Reader) error {
Sure... dropping it.

2023-02-16 14:04 UTC, nettoclaudio commented on tsuru/client/archiver.go
> +		if !strings.HasPrefix(abs, workingDir) {
Nice catch! Changing it.

2023-02-16 14:56 UTC, nettoclaudio commented on tsuru/client/archiver.go
> +		fmt.Fprintf(a.stderr, "File %q matches with some pattern provided in the ignore file... skipping it.\n", filename)
Yeah, I agree... So I'll take advantage of the `tsuru -v <number>` argument to define if it's running in debug mode. Do you see any problem about this approach?

2023-02-16 14:58 UTC, tcarreira commented on tsuru/client/archiver.go
> +		fmt.Fprintf(a.stderr, "File %q matches with some pattern provided in the ignore file... skipping it.\n", filename)
I think that's a very good approach 👍

2023-02-16 15:26 UTC, tcarreira approved these changes
Fantastic ❤️

2023-02-17 13:57 UTC, merged